[package]
name = "print-forge-pdf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
lopdf.workspace = true
print-forge-engine.workspace = true
print-forge-template.workspace = true
printpdf.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true

[[bench]]
name = "image_heavy_pages"
harness = false
