[package]
name = "print-forge-pdf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
print-forge-engine.workspace = true
print-forge-template.workspace = true
printpdf.workspace = true

[lints]
workspace = true
